### ISSUE TITLE
Look Into Internal Optimizations

### ISSUE THREAD

**Issue by jprichardson** [cryptocoinjs/bigi#2]
There was some discussion about changing this to be backed by a `Buffer`. I think that'll actually be slower since operations will then be preformed on a 8 bit numbers as opposed to what it uses now.

By analyzing the code, it does appear to in fact take advantage of JavaScript's capability of handling integers up to 53 bits. So porting to JavaScript native typed arrays may actually introduce a performance penalty. 

Maybe there may be a way to leverage some of the concepts of asm.js? Not sure. It's worth looking at potential changes and benchmarking them.

**Comment by dcousens** [comment]
> By analyzing the code, it does appear to in fact take advantage of JavaScript's capability of handling integers up to 53 bits. So porting to JavaScript native typed arrays may actually introduce a performance penalty.

Indeed, it would.

I think I'll close this,  none of us are going to look into optimisations given what we know now with `bn.js`.
