### ISSUE TITLE
Need isBigInteger

### ISSUE THREAD

**Issue by jcalfee** [cryptocoinjs/bigi#20]
Can we add isBigInteger?  As a work-around, what do you recommend?

**Comment by dcousens** [comment]
A work around for?

**Comment by jcalfee** [comment]
My API supports strings or BigIntegers.  So, how may I detect of an object is a BigInteger?

**Comment by dcousens** [comment]
`object instanceof BigInteger`?

However, this can be perilous (as a public API) if not done correctly, and you may want duck typing instead.
I suggest you do your best to remove type assertions if possible.

**Comment by jprichardson** [comment]
I'd recommend the following for your case:

```js
function isBigInteger(obj) {
  return typeof obj === 'object'
    ? obj.constructor.name === 'BigInteger'
    :  false
}
```

If you want it to work on old browsers, drop in a `Function.name` polyfill. I'm open to adding a `isBigInteger` function.

**Comment by jprichardson** [comment]
This was resolved in: https://github.com/cryptocoinjs/bigi/pull/12
