### ISSUE TITLE
Passing a Buffer into BigInteger Constructor?

### ISSUE THREAD

**Issue by jprichardson** [cryptocoinjs/bigi#22]
For reference: https://github.com/cryptocoinjs/ecurve/issues/25

@dcousens thoughts?

**Comment by dcousens** [comment]
I think we should just make it stricter,  and let people use `fromBuffer`?

**Comment by jprichardson** [comment]
Agreed. I like your idea just restricting the use of the constructor and forcing the use of the factory methods.

**Comment by dcousens** [comment]
It should be a matter of just changing the `module.exports` to
``` javascript
module.exports = {
  fromHex: BigInteger.fromHex,
  fromInt: BigInteger.fromInt, // new?
  fromBuffer: BigInteger.fromBuffer,
  fromString: BigInteger.fromString // new?
}
```

I think?
Naturally the tests will need to change too.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/cryptocoinjs/bigi/pull/27
