### ISSUE TITLE
new BigInteger(1) fails

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/bigi#23]
``` javascript
     TypeError: Cannot read property 'nextBytes' of undefined
      at BigInteger.bnpFromNumber [as fromNumber] (node_modules/bigi/lib/bigi.js:775:6)
      at new BigInteger (node_modules/bigi/lib/bigi.js:7:36)
```

Is it meant to be supported?

**Comment by jprichardson** [comment]
The constructor interface is garbage.

```js
var BigInteger = require('bigi')
var a = new BigInteger('1')
var b = new BigInteger('2')
var c = a.add(b)
console.log(c.toString()) // => 3
```

If you thought it'd make sense to tidy and fix, I'd entertain the idea. But at this point, I'd prefer to start focusing on BN.js.

Thoughts?

**Comment by dcousens** [comment]
I think, we should just remove the crappy parts of it, such that we don't get bugged by it in future (assuming you don't unpublish this module).

**Comment by jprichardson** [comment]
> I think, we should just remove the crappy parts of it,

I'd like to do this, but at what cost? Are you thinking of trimming down the module? Improving the constructor (preventing constructor)?

> (assuming you don't unpublish this module).

Not gonna happen dude :stuck_out_tongue:

**Comment by dcousens** [comment]
> Are you thinking of trimming down the module? Improving the constructor (preventing constructor)?

I think that would be a great choice.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/cryptocoinjs/bigi/pull/27
