### ISSUE TITLE
bigi flow definitions

### ISSUE THREAD

**Issue by runn1ng** [cryptocoinjs/bigi#24]
I have added bigi flow definitions here

https://github.com/flowtype/flow-typed/pull/205

(not really an issue, just wanting to let you know)

**Comment by runn1ng** [comment]
I am not sure if I should add "protected" things like `isEven()` there - it is used in ecurve tests, for example, so it is not really *that* protected....

**Comment by jprichardson** [comment]
Cool, thanks for the notice!
