### ISSUE TITLE
bnModInverse() sometimes returns negative numbers; it shouldn't

### ISSUE THREAD

**Issue by dooglus** [cryptocoinjs/bigi#25]
See https://github.com/pointbiz/bitaddress.org/issues/132

The same issue exists in this repository.

**Comment by jprichardson** [comment]
@dooglus thanks for dropping by to point this out!

**Comment by dooglus** [comment]
No problem. I don't know how common it is that `bnModInverse()` returns the wrong result, but when it does it can cause the incorrect public key (and hence, address) to be used, resulting in unspendable funds. So it's kind of a big deal.

**Comment by jprichardson** [comment]
You bet. In the process of fixing.

**Comment by jprichardson** [comment]
Thanks again @dooglus. Waiting for another pair of eyes from @dcousens. PR submitted: https://github.com/cryptocoinjs/bigi/pull/26

**Comment by dooglus** [comment]
A couple of test cases for you. Try bnModInverse on these two numbers:

    88888888888888888888888888888888888888888888888888888888000cf80a
    8888888888888888888888888888888888888888888888888888888800066783

The result from the first is too big, and needs 3 subtractions to get it within range.
The result from the second second is too small, and needs 5 additions to get it within range.

I tested 30 million pseudorandom inputs, and found that only 37 of them would have produced incorrect results. A couple of them:

`244846d2bdb089caa3ff959ec339ab85d4e32cb6a7770fa1c12c9f329f9a40c9` needs 2 subtractions, `1c1a6c8e17d42854598bcffc3344e32bfa21764bd9a506c9bef5c460ee0abe39` needs 3 additions.

**Comment by dcousens** [comment]
How did this not turn up in fuzzing? I've tried multi-millions of addresses and never come across this
