### ISSUE TITLE
Wrong instantiation of BigInteger from buffers and hex for negative numbers

### ISSUE THREAD

**Issue by RayzRazko** [cryptocoinjs/bigi#31]
Seems like there are issues in converting buffers to BigInteger instances. 
Below you can see the sample code example and the output of it in node.js environment.
```
'use strict';
const BigInteger = require('bigi');
const bigNegativeNumberString = '-12345678900';
const bigIRepresentation = new BigInteger(bigNegativeNumberString);

console.log([
    bigIRepresentation.toString(),
    BigInteger.fromBuffer(bigIRepresentation.toBuffer()).toString(),
    BigInteger.fromHex(bigIRepresentation.toHex()).toString()
]);
```
Output:
`[ '-12345678900', '1087165948876', '1087165948876' ]`

**Comment by fanatid** [comment]
@RayzRazko if you want use this library in project which is not use bigi, please use bn.js instead
https://github.com/indutny/bn.js

**Comment by RayzRazko** [comment]
Why was this issue marked as question and closed? There is an issue of converting buffer and hex representation of negative numbers in the bigi module. 
@fanatid why are you sending me to different library while I reporting about issues in this one? bn.js, btw, has same issues.

**Comment by dcousens** [comment]
@RayzRazko the hex representation doesn't support signed numbers,  basically.

`fromBuffer` is equivalent to `fromByteArrayUnsigned`

**Comment by RayzRazko** [comment]
@dcousens , are you saying that there is no way to save negative big integer into byte array with bigi module?

**Comment by dcousens** [comment]
@RayzRazko `fromByteArray` and `toByteArray` should work,  but `toBuffer` / `fromBuffer` force unsigned.
