### ISSUE TITLE
Inconsistent output with gatsby on production build

### ISSUE THREAD

**Issue by arualana** [cryptocoinjs/bigi#35]
I have a private key of type buffer.

In my local env, when running `gatsby build` the line `BigInteger.fromBuffer(privateKey)` console logs this:

`BigInteger {0: 5218218, 1: 6291014, 2: 34656281, 3: 1776116, 4: 53518743, 5: 10808093, 6: 62725491, 7: 63913863, 8: 50275223, 9: 1979384, t: 10, s: 0}`

When I am in production, run with `gatsby build`, the same exact line outputs this:

`n {0: 5218218, 1: 6291014, 2: 34656281, 3: 1776116, 4: 53518743, 5: 10808093, 6: 62725491, 7: 63913863, 8: 50275223, 9: 1979384, t: 10, s: 0}`

so the ecsda signature fails, saying it expects a `BigInteger` and is receiving type `n`

**Comment by junderw** [comment]
Use `--no-uglify` or figure out how to whitelist certain function names to prevent uglify (scrambling) the name of BigInteger.

This is an issue with your gatsby configuration, not this library.

Thanks for the issue.
